### ISSUE TITLE
Auto fix self model not working on newer versions of BlockBench

### ISSUE THREAD

**Issue by PatrikX23** [LoneDev6/cosmeticscore-editor#1]
**BlockBench Version:**
4.6.4 (Latest version)

**Older BlockBench Version:**
Works on this version: 4.5.0-Beta Version

**BlockBench Error Log:**
![image](https://user-images.githubusercontent.com/55624438/221366007-f2f43726-2619-4cfe-8d73-5ecb16e99201.png)

**Video of the issue:**
https://www.youtube.com/watch?v=OIe4IOmac1A

**Comment by LoneDev6** [comment]
Will be checked as soon as possible, thanks!
